# Powered by Websoft9

version: '3.8'

services:
  mongocompass:
    image: websoft9dev/mongocompass:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - '${APP_PORT}:6901'
    environment:
      - VNC_PW=$APP_PASSWORD

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    profiles:
      - db

networks:
  default:
      name: ${APP_NAME}

volumes:
  mongocompass:
